### ISSUE TITLE
Error responses trapped in console

### ISSUE THREAD

**Issue by acrosman** [acrosman/electronForce#15]
Error are routed to the console now and nothing appears in the interface.

**Comment by hwilson2563** [comment]
I would love to help with this bug, do you wish for an alert or how would you like to display these errors? Do you happen to have a specific example?

**Comment by acrosman** [comment]
I should probably have been more clear in the description.  In the main window you'll find a div couple things that should work better here.

First there is a function in render.js `displayRawResponse()` that should be displaying the raw API response in the interface.  On errors it doesn't do anything.

There is also a with id `results-message-only` which is meant to display messages from the action the user just attempted (hopefully successfully).  That seems like the sensible place to display the error message that came back. I'm open to other suggestions for this behavior.

**Comment by hwilson2563** [comment]
I will move forward with rendering this in the `raw response` area. Thanks for the insight!

**Comment by hwilson2563** [comment]
So looking more into this, is this only on the login fail or this specific with any call error message?
