### ISSUE TITLE
Fix Screenshots in README file

### ISSUE THREAD

**Issue by acrosman** [acrosman/electronForce#22]
**Describe the bug**
All the images in the readme file appear to have stopped working. The images should all be present in the repo so they should be an easy fix.

**Comment by Kartikeyyadav7** [comment]
## Hey I am a beginner in open source, I have fixed the screenshot issue do check it out

**Comment by Kartikeyyadav7** [comment]
### Fixed Screenshots in Readme File #24 , I am a beginner so please do let me know what else can I help with, Thank You

**Comment by acrosman** [comment]
Thanks to everyone who offered PRs on this.  I don't think it matters, but I'll leave the unmerged ones open for Hacktoberfest to make sure everyone gets credit.
