### ISSUE TITLE
Fix notice about incorrect Content Security Policy on Console page

### ISSUE THREAD

**Issue by acrosman** [acrosman/electronForce#31]
**Describe the bug**
When you start up the app the console window throw a Content Security Policy warning and refuses to load Google fonts.

> Refused to load the stylesheet 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

Requires an update to the content policy meta tag. See the main index.html file for solution.

**Comment by parthnamdev** [comment]
may i have a look on the issue?

**Comment by chAlekhya** [comment]
@acrosman I'll be glad to work on this :)

**Comment by acrosman** [comment]
@chAlekhya looks like there is already a pull request related to this issue.  I know you're eager for things to work on, but you may find it useful to review the issue discussions to look for related work.
