### ISSUE TITLE
Fix Content Security Policy for images

### ISSUE THREAD

**Issue by acrosman** [acrosman/electronForce#32]
**Describe the bug**
Both windows throw an error from an image that's violating policy. Update the content security policy meta tags to resolve.

> index.html:1 Refused to load the image 'data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='4' height='5' viewBox='0 0 4 5'%3e%3cpath fill='%23222' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by parthnamdev** [comment]
changing to 'img-src data: ' may solve. I am making a pull request. Hope it helps
