### ISSUE TITLE
Npm package

### ISSUE THREAD

**Issue by hwilson2563** [acrosman/electronForce#36]
**Describe the bug**
npm install throws an error with the node version 13.11.0

**To Reproduce**
1. run npm install
2. `` npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz
npm ERR! 404 
npm ERR! 404  'es-abstract@1.14.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'electronForce'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`` view the following error

**Expected behavior**
I tried re-installing several times

**Screenshots**
![image](https://user-images.githubusercontent.com/32081469/95614151-0f86c600-0a34-11eb-9c22-99031007c62f.png)

**Desktop (please complete the following information):**
 - MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports) Version 10.15.7 Catalina
**Additional context**
I believe I have solved this by rebuilding the package-lock pr incoming.

**Comment by acrosman** [comment]
Huh, I'll have to go back and look. I think es-abstract was recently added during one of the updates. It may not have a node 13 version (I have 14 on my machine) Either way thanks for the report and PR. I'll experiment with it a little and see what I can learn.

If you run into other issues, have feature suggestions or contributions please feel welcome to offer them up.

**Comment by acrosman** [comment]
Thank you for reporting this issue. I offered suggestions for a more stable solution. On your side I suggest you upgrade your node to a supported version. Node 13 reached end of life in June 2020. Homebrew should make it easy for your to update.
