### ISSUE TITLE
Update README Screenshots

### ISSUE THREAD

**Issue by acrosman** [acrosman/electronForce#38]
The current README screenshots are from an earlier version that displayed both the authentication fields differently and the raw response differently.  New screenshots would be helpful.

**Comment by acrosman** [comment]
Please note, you will need to be able to connect to a Salesforce org to create screenshots. I highly recommend you do _not_ use a production org or orgs with real data when creating these.  Consider a Salesforce Trailhead org instead.

**Comment by sayuree** [comment]
Can you please assign this issue to me as well?

**Comment by acrosman** [comment]
@sayuree You're assigned.
